### ISSUE TITLE
Running model with torch 1.x

### ISSUE THREAD

**Issue by SynStratos** [ziwei-zh/CorrPM#9]
Hi,
could you suggest a solution to run the evaluation with pytorch 1? I would like to try it on Colab but installing torch 0.4.1 generates problem with Cuda so it is a bit problematic.

The main problem is related to the libs modules but I can't find a complete solution to it :(

**Comment by ziwei-zh** [comment]
Hi, I have not tested it on pytorch1, but you can refer to the following line in CE2P repo (https://github.com/liutinglt/CE2P):
```
to use Pytorch 1.0, just replace 'libs' with 'modules' in https://github.com/mapillary/inplace_abn, and rename it to 'libs'.
```

**Comment by SynStratos** [comment]
Yep, I tried to do so but doesn't solve the missing _wrap_function in the lib/_ext init :( 
Do you have any idea what could be the correct substitute?

**Comment by ziwei-zh** [comment]
Could you show the errors?

**Comment by BLOO69** [comment]
Hi, I believe this is the same error.

[Traceback (most recent call last):
  File "evaluate.py", line 13, in <module>
    from networks.model import CorrPM_Model
  File "/home/student/Documents/CorrPM/networks/model.py", line 7, in <module>
    from networks.non_local import NONLocalBlock2D
  File "/home/student/Documents/CorrPM/networks/non_local.py", line 7, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/student/Documents/CorrPM/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/student/Documents/CorrPM/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/student/Documents/CorrPM/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/student/Documents/CorrPM/libs/_ext/__init__.py", line 2, in <module>
    from torch.utils.ffi import _wrap_function
  File "/home/student/anaconda3/envs/CORR/lib/python3.6/site-packages/torch/utils/ffi/__init__.py", line 1, in <module>
    raise ImportError("torch.utils.ffi is deprecated. Please use cpp extensions instead.")
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.](url)

### Dependecies
Pytorch == 1.7.0
CUDA == 10.2.89
CUDNN == 7.6.5_0

When i run nvcc: CUDA == 10.2.89
When i print torch.cuda.is_available() = True

### Analysis
It seems that this error is specific for pytorch versions above 0.4.1.  How would i be able to use this repo successfully? 

If i try to install the dependencies based on environment.yaml:
[Traceback (most recent call last):
  File "evaluate.py", line 13, in <module>
    from networks.model import CorrPM_Model
  File "/home/student/Documents/CorrPM/networks/model.py", line 7, in <module>
    from networks.non_local import NONLocalBlock2D
  File "/home/student/Documents/CorrPM/networks/non_local.py", line 7, in <module>
    from libs import InPlaceABN, InPlaceABNSync
  File "/home/student/Documents/CorrPM/libs/__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNWrapper, InPlaceABNSync, InPlaceABNSyncWrapper
  File "/home/student/Documents/CorrPM/libs/bn.py", line 15, in <module>
    from .functions import inplace_abn, inplace_abn_sync
  File "/home/student/Documents/CorrPM/libs/functions.py", line 5, in <module>
    from . import _ext
  File "/home/student/Documents/CorrPM/libs/_ext/__init__.py", line 3, in <module>
    from .__ext import lib as _lib, ffi as _ffi
ImportError: /home/student/Documents/CorrPM/libs/_ext/__ext.so: undefined symbol: __cudaRegisterFatBinaryEnd
](url)

This is most likely due to the CUDA = 9.0. I appreciate your help!

**Comment by xinzi2018** [comment]
i have the same questions

**Comment by Deepak2405** [comment]
Is this issue solved? I am having same error
